---
layout: cv
title: Kaiana Bolton's Resume
---
# Kaiana Bolton
Aspiring Accountant and Future CPA

<div id="webaddress">
<a href="kaiana.bono@gmail.com">kaiana.bono@gmail.com</a>
| <a href="https://www.linkedin.com/in/kaiana-bolton-bono-ab1a6029b/">My LinkedIn</a>


## Currently

Full time student at BYU-Idaho. Anticipated graduation date: July 2026.

### Experience with

Excel, IDEA, Altryx, and Other Audit documentation software.

## Education

`Graduated May 2021`
__Aberdeen High School__

- Valedictorian.
- Honors Society President for 2020-2021.

`August 2021 - June 2024`
__Idaho State University__

- Bachelor of Science in Accounting.
- Student Volunteer, ISU Volunteer Income Tax Assistance (VITA).

`September 2024 - Present`
__Brigham Young University-Idaho__

- Bachelor of Science in Accounting.
- Certificate in Data Science.

## Experience

`January 2025 - April 2025`
__WSRP-Now Richey May Utah__, Audit Intern, Salt Lake City, UT

- Collaborated in planning and executing financial audits, including substantive testing, analytical procedures, and internal control evaluations for clients across various industries.
- Analyzed financial statements, tested transactions, and evaluated internal controls to support compliance with GAAP and regulatory standards.
- Prepared workpapers, documented audit findings, and collaborated with senior auditors on risk assessments.
- Utilized audit software and Excel to prepare workpapers, review supporting documentation, and assist with testing procedures.

`October 2022 - August 2023`
__Idaho Central Credit Union__, Customer Service Specialist, Chubbuck, ID

- Communicated with members to resolve account concerns, maintain relationships, and deliver high-quality customer service.
- Selected for a specialized team to handle escalated member disputes and provide timely issue resolution.

`September 2021 - October 2021`
__Thompson Farms__, Truck Driver, Pinegree, ID

- Operated a 10-wheel truck during potato and beet harvest to transport crops efficiently and safely.
- Transferred harvested goods from fields to storage facilities to support time-sensitive harvest operations.

`September 2020 - May 2021`
__Wallace Drug__, Retail Clerk/Cashier, Aberdeen, ID

- Processed customer transactions for purchases, returns, and exchanges accurately and
efficiently.
- Answered incoming calls and directed customers to correct department or staff member.
- Maintained store organization by cleaning, stocking shelves, and collaborating with team members to support daily operations.

`September 2011 - October 2019`
__COMA Farms__, Laborer, Aberdeen, ID

- Worked in seasonal potato harvests for eight consecutive years, contributing approximately two and a half weeks each season.
- Operated potato piler equipment for harvest and sorting operations.



<!-- ### Footer

Last updated: Mar 2026 -->